

services:
    mongo:
        image: mongo:8.0
        container_name: mongodb
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
            MONGO_INITDB_DATABASE: journaldb
        command: ["mongod", "--auth", "--bind_ip_all"]
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:

