spring.application.name=domainmodel



# PostgreSQL Database

spring.datasource.url=jdbc:postgresql://localhost:5432/learnjpa
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# create schema everytime the application starts
spring.jpa.hibernate.ddl-auto=create-drop

# show sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



